FROM node:16.13.1-alpine

WORKDIR /app
COPY ./apps/api/ ./apps/api/
COPY ./libs/common/ ./libs/common/
COPY ./package*.json ./
COPY ./tsconfig.json ./
RUN npm ci

WORKDIR /app/apps/api
RUN npm run build

CMD ["npm", "run", "start:prod"]
