FROM node:16.13.1-alpine AS builder

WORKDIR /app
COPY ./apps/main/ ./apps/main/
COPY ./libs/common/ ./libs/common/
COPY ./scripts/ ./scripts/
COPY ./package*.json ./
COPY ./tsconfig.json ./
RUN echo "PK_API_URL_PROD=http://api:8100" > ./.env
RUN npm ci && npm run build:main

FROM nginx:alpine

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/apps/main/dist/main/ .
ENTRYPOINT ["nginx", "-g", "daemon off;"]
